export const US_STATES = [
	{ value: "AL", label: "Alabama" },
	{ value: "AK", label: "Alaska" },
	{ value: "AZ", label: "Arizona" },
	{ value: "AR", label: "Arkansas" },
	{ value: "CA", label: "California" },
	{ value: "CO", label: "Colorado" },
	{ value: "CT", label: "Connecticut" },
	{ value: "DE", label: "Delaware" },
	{ value: "DC", label: "District of Columbia" },
	{ value: "FL", label: "Florida" },
	{ value: "GA", label: "Georgia" },
	{ value: "HI", label: "Hawaii" },
	{ value: "ID", label: "Idaho" },
	{ value: "IL", label: "Illinois" },
	{ value: "IN", label: "Indiana" },
	{ value: "IA", label: "Iowa" },
	{ value: "KS", label: "Kansas" },
	{ value: "KY", label: "Kentucky" },
	{ value: "LA", label: "Louisiana" },
	{ value: "ME", label: "Maine" },
	{ value: "MD", label: "Maryland" },
	{ value: "MA", label: "Massachusetts" },
	{ value: "MI", label: "Michigan" },
	{ value: "MN", label: "Minnesota" },
	{ value: "MS", label: "Mississippi" },
	{ value: "MO", label: "Missouri" },
	{ value: "MT", label: "Montana" },
	{ value: "NE", label: "Nebraska" },
	{ value: "NV", label: "Nevada" },
	{ value: "NH", label: "New Hampshire" },
	{ value: "NJ", label: "New Jersey" },
	{ value: "NM", label: "New Mexico" },
	{ value: "NY", label: "New York" },
	{ value: "NC", label: "North Carolina" },
	{ value: "ND", label: "North Dakota" },
	{ value: "OH", label: "Ohio" },
	{ value: "OK", label: "Oklahoma" },
	{ value: "OR", label: "Oregon" },
	{ value: "PA", label: "Pennsylvania" },
	{ value: "RI", label: "Rhode Island" },
	{ value: "SC", label: "South Carolina" },
	{ value: "SD", label: "South Dakota" },
	{ value: "TN", label: "Tennessee" },
	{ value: "TX", label: "Texas" },
	{ value: "UT", label: "Utah" },
	{ value: "VT", label: "Vermont" },
	{ value: "VA", label: "Virginia" },
	{ value: "WA", label: "Washington" },
	{ value: "WV", label: "West Virginia" },
	{ value: "WI", label: "Wisconsin" },
	{ value: "WY", label: "Wyoming" },
]

export const LANGUAGE_OPTIONS = [
	{ value: "english", en: "English", es: "Inglés" },
	{ value: "spanish", en: "Spanish", es: "Español" },
	{ value: "french", en: "French", es: "Francés" },
	{ value: "german", en: "German", es: "Alemán" },
	{ value: "italian", en: "Italian", es: "Italiano" },
	{ value: "portuguese", en: "Portuguese", es: "Portugués" },
	{ value: "russian", en: "Russian", es: "Ruso" },
	{ value: "mandarin", en: "Mandarin", es: "Mandarín" },
	{ value: "cantonese", en: "Cantonese", es: "Cantonés" },
	{ value: "vietnamese", en: "Vietnamese", es: "Vietnamita" },
	{ value: "tagalog", en: "Tagalog", es: "Tagalo" },
	{ value: "korean", en: "Korean", es: "Coreano" },
	{ value: "japanese", en: "Japanese", es: "Japonés" },
	{ value: "arabic", en: "Arabic", es: "Árabe" },
	{ value: "navajo", en: "Navajo / Diné", es: "Navajo / Diné" },
	{ value: "other", en: "Other", es: "Otro" },
]

// Standard OMB race/ethnicity categories
export const RACE_ETHNICITY_OPTIONS = [
	{
		value: "hispanic-latino",
		en: "Hispanic or Latino",
		es: "Hispano o Latino",
	},
	{
		value: "white",
		en: "White (non-Hispanic)",
		es: "Blanco (no Hispano)",
	},
	{
		value: "black",
		en: "Black or African American",
		es: "Negro o Afroamericano",
	},
	{
		value: "asian",
		en: "Asian",
		es: "Asiático",
	},
	{
		value: "american-indian",
		en: "American Indian or Alaska Native",
		es: "Indígena Americano o Nativo de Alaska",
	},
	{
		value: "pacific-islander",
		en: "Native Hawaiian or Other Pacific Islander",
		es: "Hawaiano Nativo u otro Isleño del Pacífico",
	},
	{
		value: "two-or-more",
		en: "Two or more races",
		es: "Dos o más razas",
	},
	{
		value: "other",
		en: "Other",
		es: "Otro",
	},
	{
		value: "prefer-not",
		en: "Prefer not to say",
		es: "Prefiero no decirlo",
	},
]

export const REFERRAL_SOURCES = [
	{ value: "physician", en: "Referred by a physician", es: "Referido por un médico" },
	{ value: "friend-family", en: "Friend or family", es: "Amigo o familiar" },
	{ value: "insurance", en: "Insurance provider", es: "Proveedor de seguro" },
	{ value: "internet", en: "Internet search", es: "Búsqueda en internet" },
	{ value: "social-media", en: "Social media", es: "Redes sociales" },
	{ value: "returning", en: "Returning patient", es: "Paciente recurrente" },
	{ value: "other", en: "Other", es: "Otro" },
]
